[[redirects]]
  from = "/api/article/"
  to = "http://www.zhuwenfu.top/api/article/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[redirects]]
  from = "/api/article/:id"
  to = "http://www.zhuwenfu.top/api/article/:id"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
