[[redirects]]
  from = "/api/*"
  to = "http://www.zhuwenfu.top"
  status = 200
  force = true
  [redirects.headers]
    X-From = "Netlify"
    X-Api-Key = "some-api-key-string"

[[headers]]
  for = "/*"
  [headers.values]
    host = 'http://www.zhuwenfu.top'
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
