[[redirects]]
  from = "/api/*"
  to = "http://www.zhuwenfu.top/api/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
